// Illustrative workflows only. Names, counts and records are examples, not shipped products, customers or results.
export const AGENTS = [
  { id: "hr", label: "HR", world: "blue", photo: "hr", head: "Hire faster. Find better.", ask: "Screen these applications for Product Designer.",
    stages: [{ k: "Task", t: "Screen 124 applications" }, { k: "AI work", t: "Reads résumés", s: "Skills · Experience · Role match" }, { k: "Result", t: "18 shortlisted" }, { k: "Human", t: "Approve · Review · Edit" }],
    ui: { type: "table", title: "Resume screening", cols: ["Candidate", "Match", "Status"], rows: [["Aarav S.", 92, ["ok", "Shortlist"]], ["Meera K.", 88, ["ok", "Shortlist"]], ["Daniel R.", 71, ["wait", "Review"]], ["Sofia L.", 54, ["no", "Not a fit"]]] },
    approve: ["Approve 18", "Review"], agents: ["Resume Screening", "Interview Scheduling", "Candidate Research", "Onboarding"] },
  { id: "finance", label: "Finance", world: "green", photo: "finance", head: "Turn paperwork into progress.", ask: "Process this invoice.",
    stages: [{ k: "Task", t: "Invoice arrives" }, { k: "AI work", t: "Extracts and matches", s: "PO · Receipt · Policy" }, { k: "Result", t: "3-way match passed" }, { k: "Human", t: "Approve payment" }],
    ui: { type: "table", title: "Invoice extraction", cols: ["Field", "Read", "Check"], rows: [["Vendor", "Northwind Supplies", ["ok", "Known"]], ["Invoice / PO", "INV-2041 / PO-8830", ["ok", "Matched"]], ["Amount", "Example value", ["ok", "In policy"]], ["Receipt", "GRN-552", ["wait", "Partial"]]] },
    approve: ["Approve", "Send back"], agents: ["Invoice Processing", "Expense Review", "Reconciliation", "Finance Reporting"] },
  { id: "procurement", label: "Procurement", world: "gold", photo: "procurement", head: "Make buying move faster.", ask: "New purchase request: 20 laptops.",
    stages: [{ k: "Task", t: "Purchase request" }, { k: "AI work", t: "Checks", s: "Budget · Policy · Supplier" }, { k: "Result", t: "Recommend: approve" }, { k: "Human", t: "Sign off" }],
    ui: { type: "table", title: "Purchase approval", cols: ["Check", "Result", ""], rows: [["Budget", "Within limit", ["ok", "Pass"]], ["Policy", "Approved category", ["ok", "Pass"]], ["Supplier", "On approved list", ["ok", "Pass"]], ["Past orders", "2 similar", ["wait", "Note"]]] },
    approve: ["Approve", "Ask supplier"], agents: ["Procurement Intake", "Supplier Research", "Purchase Order", "Contract Review"] },
  { id: "sales", label: "Sales", world: "blue", photo: "sales", head: "Know the account first.", ask: "Prepare me for tomorrow's call.",
    stages: [{ k: "Task", t: "Lead needs a brief" }, { k: "AI work", t: "Researches", s: "Company · Decision makers" }, { k: "Result", t: "Account brief" }, { k: "Human", t: "Confirm CRM update" }],
    ui: { type: "brief", title: "Account brief", lines: [["Company", "Collected"], ["Decision makers", "3 found"], ["Past contact", "Summarised"], ["Next step", "Draft follow-up ready"]] },
    approve: ["Update CRM", "Edit email"], agents: ["Lead Research", "Email Drafting", "Follow-up", "CRM Update"] },
  { id: "marketing", label: "Marketing", world: "red", photo: "marketing", head: "From brief to campaign.", ask: "Plan the spring launch.",
    stages: [{ k: "Task", t: "Brand brief" }, { k: "AI work", t: "Researches and drafts", s: "Trends · Copy · Calendar" }, { k: "Result", t: "5 drafts" }, { k: "Human", t: "Approve to publish" }],
    ui: { type: "cal", title: "Content calendar", days: ["Mon", "Tue", "Wed", "Thu", "Fri"], items: [["Mon", "Teaser reel", "ok"], ["Wed", "Founder post", "wait"], ["Thu", "Product film", "ok"], ["Fri", "Recap", "no"]] },
    approve: ["Approve all", "Review"], agents: ["Campaign Planning", "Content Drafting", "Audience Insight", "Performance Summary"] },
  { id: "it", label: "IT", world: "blue", photo: "it", head: "Fix issues sooner.", ask: "I can't access the VPN.",
    stages: [{ k: "Task", t: "Employee request" }, { k: "AI work", t: "Checks", s: "Identity · Access · Status" }, { k: "Result", t: "Access restored" }, { k: "Human", t: "Escalates only if needed" }],
    ui: { type: "chat", title: "IT helpdesk", msgs: [["me", "I can't access the VPN."], ["ai", "Your access is active. I reset the session. Try again now."], ["me", "Works, thanks."], ["ai", "Done. No ticket needed."]] },
    approve: ["Resolved", "Open ticket"], agents: ["IT Helpdesk", "Access Request", "Ticket Triage"] },
  { id: "service", label: "Customer Service", world: "green", photo: "support", head: "Answer every customer.", ask: "My order hasn't arrived.",
    stages: [{ k: "Task", t: "Customer message" }, { k: "AI work", t: "Understands and checks", s: "Order · Policy · History" }, { k: "Result", t: "Reply sent" }, { k: "Human", t: "Escalates if required" }],
    ui: { type: "chat", title: "Support inbox", msgs: [["me", "My order hasn't arrived."], ["ai", "It shipped and is 2 days late. I've offered a refund or a re-ship."], ["me", "Re-ship please."], ["ai", "Done. A teammate will confirm the date."]] },
    approve: ["Send", "Hand to a person"], agents: ["Customer Support", "Case Summary", "Ticket Routing", "Follow-up"] },
  { id: "ops", label: "Operations", world: "gold", photo: "operations", head: "See problems early.", ask: "Watch orders, stock and tasks.",
    stages: [{ k: "Task", t: "Monitor the business" }, { k: "AI work", t: "Detects and investigates" }, { k: "Result", t: "3 issues ranked" }, { k: "Human", t: "Pick the action" }],
    ui: { type: "table", title: "Operations watch", cols: ["Issue", "Impact", "Action"], rows: [["Stock low, SKU 114", "High", ["hot", "Reorder"]], ["Late shipments", "Medium", ["wait", "Review"]], ["Task backlog", "Low", ["no", "Monitor"]]] },
    approve: ["Reorder", "Review"], agents: ["Operations Monitoring", "Task Coordination", "Exception Handling"] },
  { id: "health", label: "Healthcare", world: "green", photo: "healthcare", head: "Give care teams time.", ask: "Review today's appointment schedule.",
    stages: [{ k: "Task", t: "Patient requests" }, { k: "AI work", t: "Checks and schedules", s: "Availability · Follow-ups" }, { k: "Result", t: "Gaps filled" }, { k: "Human", t: "Staff review. Clinicians decide." }],
    ui: { type: "table", title: "Scheduling", cols: ["Time", "Slot", "Status"], rows: [["10:00", "Follow-up due", ["wait", "Suggested"]], ["10:30", "Open slot", ["ok", "Filled"]], ["11:00", "Long wait", ["hot", "Flagged"]]] },
    approve: ["Confirm", "Edit"], agents: ["Patient Scheduling", "Clinical Documentation", "OPD Operations", "Patient Follow-up"] },
];
