import { AGENT_MEDIA as M } from "@/lib/media";
// Illustrative workflows only. Names, numbers and records below are examples, not shipped products, customers or metrics.
export const TABS = [
  { id: "hr", icon: "Users", label: "HR", full: "Human Resources", title: "Hire faster. Find better.", line: "AI agents that help your team move from applications to onboarding.", img: M.hr,
    chip: ["AI Screening Agent", "124 applications", "18 shortlisted"], ask: "Screen these applications for the Product Designer role.",
    facts: [["Candidate", "Aarav Sharma"], ["Role", "Product Designer, 8 yrs"], ["Skills", "Figma · UX · AI"]],
    steps: ["Reading the role requirements", "Analyzing 124 applications", "Checking experience, skills, relevance"], result: ["18 candidates shortlisted", "Next: schedule interviews with the top 5."],
    agents: [["Resume Screening", "Screens CVs against job requirements."], ["Interview Scheduling", "Coordinates calendars and availability."], ["Candidate Research", "Builds a brief before each interview."], ["Employee Onboarding", "Coordinates documents, training and tasks."]] },
  { id: "service", icon: "MessageSquare", label: "Customer Service", full: "Customer Service", title: "Resolve requests automatically.", line: "Answers that come from your own order, policy and customer data.", img: M.service,
    chip: ["Support Agent", "Order delayed", "Reply ready"], ask: "“My order hasn’t arrived yet.”",
    facts: [["Order", "Shipped, in transit"], ["Delay", "2 days"], ["Policy", "Refund applicable"]],
    steps: ["Searching the order", "Checking delivery status", "Reviewing customer history"], result: ["Resolution found. Ticket resolved.", "Reply drafted: delay explained, refund offered."],
    agents: [["Customer Support", "Answers and resolves common requests."], ["Case Summary", "Summarizes long threads for handover."], ["Ticket Routing", "Sends each case to the right team."], ["Customer Intent", "Works out what the customer needs."], ["Follow-up", "Checks back after the issue is closed."]] },
  { id: "finance", icon: "Receipt", label: "Finance", full: "Finance", title: "Turn paperwork into progress.", line: "Read the invoice, check it against the order, route it for approval.", img: M.finance,
    chip: ["Invoice Agent", "Invoice read", "3-way match"], ask: "Process this invoice.",
    facts: [["Vendor", "Northwind Supplies"], ["Invoice / PO", "INV-2041 / PO-8830"], ["Amount + tax", "Example values"]],
    steps: ["Reading vendor, number, amount, tax", "Matching purchase order ✓", "Matching invoice ✓ and receipt ✓"], result: ["Ready for approval", "Passed the 3-way match. Waiting on a person."],
    agents: [["Invoice Processing", "Reads and codes incoming invoices."], ["Expense Review", "Checks claims against policy."], ["Finance Reporting", "Assembles the monthly numbers."], ["Reconciliation", "Matches records across systems."], ["Anomaly Detection", "Flags what looks unusual."]] },
  { id: "procurement", icon: "ShoppingCart", label: "Procurement", full: "Procurement", title: "Make procurement move faster.", line: "Every purchase request checked before it reaches a person.", img: M.procurement,
    chip: ["Procurement Agent", "Request checked", "Approve"], ask: "New purchase request: 20 laptops.",
    facts: [["Request", "20 laptops"], ["Budget", "Within limit"], ["Vendor", "Approved list"]],
    steps: ["Checking policy", "Checking vendor and budget", "Reviewing previous purchases"], result: ["Recommendation: Approve", "Supplier message drafted for your review."],
    agents: [["Procurement Intake", "Collects and completes requests."], ["Supplier Research", "Compares vendors and past orders."], ["Purchase Order", "Prepares the order for sign-off."], ["Vendor Communication", "Drafts supplier emails."], ["Contract Review", "Highlights terms that need a person."]] },
  { id: "sales", icon: "TrendingUp", label: "Sales", full: "Sales", title: "Turn leads into action.", line: "Know the account before the call, and never forget the follow-up.", img: M.sales,
    chip: ["Sales Agent", "Account researched", "Brief ready"], ask: "Prepare me for tomorrow’s call with this account.",
    facts: [["Company info", "Collected"], ["Recent news", "Reviewed"], ["Past contact", "Summarized"]],
    steps: ["Researching the account", "Finding decision makers", "Reading previous interactions"], result: ["Account brief ready", "Follow-up email drafted. CRM update waiting for you."],
    agents: [["Lead Research", "Builds an account brief."], ["Email Drafting", "Writes the first version in your voice."], ["Follow-up", "Suggests the next step."], ["CRM Update", "Keeps records current."]] },
  { id: "marketing", icon: "Megaphone", label: "Marketing", full: "Marketing", title: "From insight to campaign.", line: "From a brief to a first draft of the whole campaign.", img: M.marketing,
    chip: ["Campaign Agent", "1 brief", "5 drafts"], ask: "Plan a spring launch campaign.",
    facts: [["Audience", "Analyzed"], ["Past campaigns", "Reviewed"], ["Performance", "Summarized"]],
    steps: ["Analyzing audience and past campaigns", "Reviewing performance data", "Drafting concept, copy, email, calendar"], result: ["Campaign draft ready", "Concept · social copy · email · content calendar."],
    agents: [["Campaign Planning", "Turns a brief into a plan."], ["Content Drafting", "Drafts copy for each channel."], ["Audience Insight", "Finds who responds and why."], ["Performance Summary", "Explains what worked."]] },
  { id: "it", icon: "Laptop", label: "IT", full: "IT", title: "Resolve IT issues faster.", line: "Common requests handled first, the rest passed on with context.", img: M.it,
    chip: ["IT Helpdesk Agent", "VPN issue", "Resolved"], ask: "“I can’t access the VPN.”",
    facts: [["User", "Identified"], ["Access", "Checked"], ["System status", "Checked"]],
    steps: ["Identifying the user and their access", "Checking system status", "Troubleshooting"], result: ["Issue resolved", "Employee notified. A ticket is created only if needed."],
    agents: [["IT Helpdesk", "Solves everyday requests."], ["Access Request", "Routes approvals and grants access."], ["Ticket Triage", "Creates and routes tickets."]] },
  { id: "ops", icon: "Activity", label: "Operations", full: "Operations", title: "Keep operations moving.", line: "An agent that watches, investigates and tells you what needs you.", img: M.ops,
    chip: ["Monitoring Agent", "3 issues", "Prioritized"], ask: "Watch orders, inventory, people and tasks.",
    facts: [["Orders", "Monitored"], ["Inventory", "Monitored"], ["Exceptions", "Flagged"]],
    steps: ["Detecting an anomaly", "Investigating the cause", "Recommending an action"], result: ["3 issues need attention", "Ranked by impact. Escalated to a person if needed."],
    agents: [["Operations Monitoring", "Observes, analyzes, escalates."], ["Task Coordination", "Keeps handoffs moving."], ["Exception Handling", "Prepares fixes for approval."]] },
  { id: "health", icon: "Stethoscope", label: "Healthcare", full: "Healthcare", title: "Give care teams more time.", line: "Administrative work off the care team’s plate. Clinical decisions stay with clinicians.", img: M.health,
    chip: ["OPD Operations Agent", "Gaps found", "Actions suggested"], ask: "Review today’s appointment schedule.",
    facts: [["Follow-ups", "1 missing"], ["Waiting time", "High, 10:00–11:00"], ["Doctor capacity", "Checked"]],
    steps: ["Reading appointments and doctor schedules", "Finding missing follow-ups", "Checking waiting time and capacity"], result: ["Actions suggested", "Staff review each one. No clinical decisions are made."],
    agents: [["Patient Scheduling", "Fills gaps and reduces waits."], ["Clinical Documentation", "Drafts notes for clinician review."], ["OPD Operations", "Watches queues and capacity."], ["Patient Follow-up", "Reminds and checks back."], ["Healthcare Support", "Answers routine patient questions."]] },
];
